// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKrP7DDwmfvFpLtO6QDSinX-Omt5sc7I',
    appId: '1:152523278613:web:3c25bf1e54ee87ca32811c',
    messagingSenderId: '152523278613',
    projectId: 'wyvernsecurity-backend',
    authDomain: 'wyvernsecurity-backend.firebaseapp.com',
    storageBucket: 'wyvernsecurity-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHoas1iEZxqxsTOh7bjJzDSFMb6fBhgmY',
    appId: '1:152523278613:android:aa1961329cee3e7832811c',
    messagingSenderId: '152523278613',
    projectId: 'wyvernsecurity-backend',
    storageBucket: 'wyvernsecurity-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9G3_WreHN5FLDqTjGd0aGoZbTJhp3ADY',
    appId: '1:152523278613:ios:a96cdaf6cad1b92132811c',
    messagingSenderId: '152523278613',
    projectId: 'wyvernsecurity-backend',
    storageBucket: 'wyvernsecurity-backend.firebasestorage.app',
    iosBundleId: 'com.example.wyvernSecurityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9G3_WreHN5FLDqTjGd0aGoZbTJhp3ADY',
    appId: '1:152523278613:ios:a96cdaf6cad1b92132811c',
    messagingSenderId: '152523278613',
    projectId: 'wyvernsecurity-backend',
    storageBucket: 'wyvernsecurity-backend.firebasestorage.app',
    iosBundleId: 'com.example.wyvernSecurityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbKrP7DDwmfvFpLtO6QDSinX-Omt5sc7I',
    appId: '1:152523278613:web:cefdfb1272b4997732811c',
    messagingSenderId: '152523278613',
    projectId: 'wyvernsecurity-backend',
    authDomain: 'wyvernsecurity-backend.firebaseapp.com',
    storageBucket: 'wyvernsecurity-backend.firebasestorage.app',
  );

}